require:
  - rubocop-rspec
AllCops:
  NewCops: enable

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - passage.gemspec
    - spec/**/*_spec.rb

RSpec/ExampleLength:
  Enabled: true
  Max: 20

RSpec/MultipleExpectations:
  Enabled: true
  Max: 5
